export const iconKey = {
  success: 'carbon:checkmark-outline',
  failed: 'carbon:warning-alt',
  toc: 'carbon:table-of-contents',
  add: 'carbon:add-large',
  search: 'carbon:search',
  link: 'carbon:link',
  unlink: 'carbon:unlink',
  trash: 'carbon:trash-can',
  area: 'carbon:area',
  setting: 'carbon:settings',
  dotMenuVertical: 'carbon:overflow-menu-vertical',

  // For editor toolbar
  textBold: 'carbon:text-bold',
  textItalic: 'carbon:text-italic',
  textStrikeThrough: 'carbon:text-strikethrough',
  listBulletted: 'carbon:list-bulleted',
  listNumbered: 'carbon:list-numbered',
  quotes: 'carbon:quotes',
  inlineCode: 'carbon:string-text',
  memoLink: 'carbon:ibm-cloud-direct-link-1-connect',

  // Titlebar
  arrowLeft: 'carbon:arrow-left',
  arrowRight: 'carbon:arrow-right',
  menu: 'carbon:menu',

  bookmark: 'carbon:bookmark',
  recent: 'carbon:recently-viewed',
  switch: 'carbon:arrows-horizontal',
  database: 'carbon:db2-database',
  chevronDown: 'carbon:chevron-down',
  home: 'carbon:home',
  copy: 'carbon:copy',
  clearFormat: 'carbon:text-clear-format',
  annotation: 'carbon:text-annotation-toggle',
  tree: 'carbon:tree-view-alt',
  html: 'carbon:html',
  pageLink: 'carbon:app-connectivity',
  shuffle: 'carbon:shuffle',

  sidebarOpen: 'carbon:side-panel-open',
  sidebarClose: 'carbon:side-panel-close',
};
