export const iconKey = {
  success: 'carbon:checkmark-outline',
  failed: 'carbon:warning-alt',
  toc: 'carbon:table-of-contents',
  add: 'carbon:add-large',
  edit: 'carbon:edit',
  search: 'carbon:search',
  quickOpen: 'carbon:search',
  fullSearch: 'carbon:search-locate',
  link: 'carbon:link',
  unlink: 'carbon:unlink',
  trash: 'carbon:trash-can',
  area: 'carbon:area',
  setting: 'carbon:settings',
  dotMenuVertical: 'carbon:overflow-menu-vertical',

  // For editor toolbar
  textBold: 'carbon:text-bold',
  textItalic: 'carbon:text-italic',
  textStrikeThrough: 'carbon:text-strikethrough',
  listBulletted: 'carbon:list-bulleted',
  listNumbered: 'carbon:list-numbered',
  quotes: 'carbon:quotes',
  inlineCode: 'carbon:string-text',
  table: 'carbon:table',
  memoLink: 'carbon:ibm-cloud-direct-link-1-connect',

  // Titlebar
  arrowLeft: 'carbon:arrow-left',
  arrowRight: 'carbon:arrow-right',
  arrowUp: 'carbon:arrow-up',
  arrowDown: 'carbon:arrow-down',
  menu: 'carbon:menu',

  bookmark: 'carbon:bookmark',
  bookmarkFilled: 'carbon:bookmark-filled',
  recent: 'carbon:recently-viewed',
  switch: 'carbon:arrows-horizontal',
  database: 'carbon:db2-database',
  folder: 'carbon:folder',
  documentAttachment: 'carbon:document-attachment',
  renew: 'carbon:renew',
  chevronDown: 'carbon:chevron-down',
  home: 'carbon:home',
  copy: 'carbon:copy',
  save: 'carbon:save',
  clearFormat: 'carbon:text-clear-format',
  annotation: 'carbon:text-annotation-toggle',
  tree: 'carbon:tree-view-alt',
  html: 'carbon:html',
  pageLink: 'carbon:app-connectivity',
  shuffle: 'carbon:shuffle',

  zoomIn: 'carbon:zoom-in',
  zoomOut: 'carbon:zoom-out',
  zoomReset: 'carbon:zoom-reset',

  close: 'carbon:close',
  openPanel: 'carbon:launch',

  sidebarOpen: 'carbon:side-panel-open',
  sidebarClose: 'carbon:side-panel-close',

  kanban: 'carbon:arrange-vertical',

  sun: 'carbon:sun',
  moon: 'carbon:moon',
};
